In [1]:
import pandas as pd
import numpy as np
from factor_analyzer import FactorAnalyzer
from sklearn.datasets import load_iris

# 데이터 로드 (예제 데이터로 아이리스 데이터 사용)
data = load_iris()
X = data.data

# 요인 분석 객체 생성
factor_analyzer = FactorAnalyzer(n_factors=3, rotation="varimax")

# 모델 피팅
factor_analyzer.fit(X)

# 요인 목록 확인
loadings = factor_analyzer.loadings_
print("Loadings:\n", loadings)

# 요인 분석 결과 시각화 등 추가적인 분석은 필요에 따라 수행할 수 있습니다.


Loadings:
 [[ 0.99595672 -0.00932682  0.03526641]
 [-0.10813897  0.75599036 -0.07988971]
 [ 0.86124923 -0.41316935  0.28730365]
 [ 0.80078824 -0.31752521  0.49423052]]


In [2]:
df = pd.read_csv('./Data/house-prices-advanced-regression-techniques/train.csv')
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
numeric_df = df.select_dtypes(include=['int', 'float'])

In [4]:
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   OverallQual    1460 non-null   int64  
 5   OverallCond    1460 non-null   int64  
 6   YearBuilt      1460 non-null   int64  
 7   YearRemodAdd   1460 non-null   int64  
 8   MasVnrArea     1452 non-null   float64
 9   BsmtFinSF1     1460 non-null   int64  
 10  BsmtFinSF2     1460 non-null   int64  
 11  BsmtUnfSF      1460 non-null   int64  
 12  TotalBsmtSF    1460 non-null   int64  
 13  1stFlrSF       1460 non-null   int64  
 14  2ndFlrSF       1460 non-null   int64  
 15  LowQualFinSF   1460 non-null   int64  
 16  GrLivArea      1460 non-null   int64  
 17  BsmtFullBath   1460 non-null   int64  
 18  BsmtHalf

In [40]:
array_df = np.array(numeric_df.iloc[:, :36])

In [37]:
# 요인 분석 객체 생성
factor_analyzer = FactorAnalyzer(n_factors=4, rotation="varimax")

# 모델 피팅
factor_analyzer.fit(array_df)

# 요인 목록 확인
loadings = factor_analyzer.loadings_
print("Loadings:\n", loadings[1])

Loadings:
 [-0.61267286  0.06858076 -0.1286787   0.03009436]


In [ ]:
# 요인 분석 객체 생성
factor_analyzer = FactorAnalyzer(n_factors=30, rotation="varimax")

# 모델 피팅
factor_analyzer.fit(array_df)

# 요인 목록 확인
loadings = factor_analyzer.loadings_
print("Loadings:\n", loadings)

In [30]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))  # 지수 함수 계산 및 최대값 보정
    return exp_x / exp_x.sum(axis=0)

# 입력 벡터
input_vector = np.array([2.0, 1.0, -2.1])

# 소프트맥스 함수 적용
output_probs = softmax(input_vector)

print("Input Vector:", input_vector)

print("Output Probabilities:", output_probs)
print("Sum of Probabilities:", np.sum(output_probs))


Input Vector: [ 2.   1.  -2.1]
Output Probabilities: [0.72230739 0.26572204 0.01197057]
Sum of Probabilities: 0.9999999999999999


In [85]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # 지수 함수 계산 및 최대값 보정
    return exp_x / exp_x.sum(axis=0)

def threshold_below(arr, threshold):
    return np.where(arr <= threshold, 0, arr)

class Factor_attention():
    def __init__(self, array:np.array, n_factors:int, dim_info:int):
        self.array = array
        self.n_factors = n_factors
        self.dim_info = dim_info
        self.n_col = len(array[0])
        self.loadings = abs(self.factor_analyzer())
        self.attention_query = np.random.rand(self.n_factors, self.dim_info)
        self.attention_key = np.random.rand(self.n_factors, self.dim_info)
        
    def factor_analyzer(self, rotation:str="varimax"):
        analyzer = FactorAnalyzer(n_factors=self.n_factors, rotation=rotation)
        analyzer.fit(self.array)
        loadings = analyzer.loadings_
        
        return loadings
    
    def attention(self, threshold:bool=False, threshold_value:float=0.1):
        query_matrix = self.loadings.dot(self.attention_query)
        key_matrix = self.loadings.dot(self.attention_key)
        attention_score = np.apply_along_axis(softmax, axis=1, arr=(query_matrix.dot(key_matrix.T)))
        
        if threshold:
            return threshold_below(attention_score, threshold_value)
        else:
            return attention_score


In [86]:
a = Factor_attention(array_df, n_factors=30, dim_info=10).attention(threshold=True)[0]
a

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.24747486, 0.        ,
       0.        , 0.25515566, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [67]:
import numpy as np

def threshold_below(arr, threshold):
    return np.where(arr <= threshold, 0, arr)

# 입력 배열
input_array = np.array([0.2, 0.05, 0.3, 0.08, 0.15])

# 0.1 이하인 값 0으로 변환
output_array = threshold_below(input_array, 0.1)

In [80]:
b = softmax(a).round(3)
b = threshold_below(b, 0.1)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [44]:
loadings.round(3)[2]

array([ 0.21 ,  0.182,  0.051,  0.134,  0.049,  0.533,  0.042,  0.016,
        0.028,  0.013,  0.095, -0.009,  0.306, -0.079, -0.026,  0.032,
       -0.014,  0.297,  0.005,  0.06 ,  0.064,  0.139, -0.035,  0.016,
       -0.054,  0.011,  0.018,  0.057, -0.047,  0.047])

In [62]:
n_factors = 30
dim_info = 10
attention_query = np.random.rand(n_factors, dim_info)
attention_key = np.random.rand(n_factors, dim_info)
attention_value = np.random.rand(n_factors, dim_info)

In [83]:
attention_query.shape[0]

30

In [55]:
loadings[1].dot(attention_query)

array([-0.44689723, -0.42585861,  0.1596977 , -0.31712499, -0.29440666,
       -0.01591192, -0.61356592, -0.42014197, -0.42260552, -0.17109384])