In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir('/content/drive/MyDrive/work_space/Project/ABFR')

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('./Data/house-prices-advanced-regression-techniques/train.csv')
numeric_df = df.select_dtypes(include=['int', 'float'])

In [2]:
numeric_df = numeric_df.dropna(axis=0)
numeric_df.reset_index(inplace=True, drop=True)
test_df = numeric_df.iloc[:, 1:23]

In [3]:
array_df = np.array(test_df)
array_df = np.round(array_df, 3)
array_df

array([[6.000e+01, 6.500e+01, 8.450e+03, ..., 1.000e+00, 3.000e+00,
        1.000e+00],
       [2.000e+01, 8.000e+01, 9.600e+03, ..., 0.000e+00, 3.000e+00,
        1.000e+00],
       [6.000e+01, 6.800e+01, 1.125e+04, ..., 1.000e+00, 3.000e+00,
        1.000e+00],
       ...,
       [7.000e+01, 6.600e+01, 9.042e+03, ..., 0.000e+00, 4.000e+00,
        1.000e+00],
       [2.000e+01, 6.800e+01, 9.717e+03, ..., 0.000e+00, 2.000e+00,
        1.000e+00],
       [2.000e+01, 7.500e+01, 9.937e+03, ..., 1.000e+00, 3.000e+00,
        1.000e+00]])

In [4]:
from util.module import *

In [5]:
fa = Factor_attention(array_df, 15, 3)
fa.col_to_vec(threshold = 0.6)

In [6]:
array_df.shape

(1121, 22)

In [7]:
fa.result 

[[0],
 [1, 2, 12],
 [3, 5, 6, 7, 11, 15, 18],
 [4],
 [3, 5, 7, 11, 12, 15],
 [8, 16],
 [9],
 [10],
 [1, 7, 11, 12],
 [13, 15, 19, 20],
 [14],
 [3, 7, 13, 15, 18, 20],
 [8, 16],
 [17],
 [21]]

In [8]:
fa.attention()

In [9]:
fa.attention_score

[[1],
 array([[1.6217192 ],
        [1.60530574],
        [1.62888488]]),
 array([[1.47301331],
        [1.45945403],
        [1.43140696],
        [1.42784997],
        [1.46733076],
        [1.48927977],
        [1.4840583 ]]),
 [1],
 array([[1.36163516],
        [1.35301634],
        [1.3334415 ],
        [1.35709096],
        [1.35331753],
        [1.36989705]]),
 array([[1.59221182],
        [1.66098656]]),
 [1],
 [1],
 array([[1.33370225],
        [1.31425214],
        [1.34102098],
        [1.33473035]]),
 array([[1.16834741],
        [1.37476703],
        [0.99739313],
        [1.27742279]]),
 [1],
 array([[1.4875939 ],
        [1.39021902],
        [1.41905048],
        [1.53515096],
        [1.52616804],
        [1.46889219]]),
 array([[1.59221182],
        [1.66098656]]),
 [1],
 [1]]

In [9]:
np.array(fa.result_idx)

array([ 0,  1,  3,  4,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 21])

In [18]:
import torch
import torch.nn as nn

attention_query = nn.Parameter(torch.randn(3, 5))

In [19]:
attention_query

Parameter containing:
tensor([[ 0.0737,  0.0511, -0.2338, -0.1723,  0.7400],
        [ 1.0627,  1.6775, -1.0736, -0.3830,  1.5741],
        [ 1.1088,  1.4790, -0.2331, -1.2336, -1.2794]], requires_grad=True)